name: Module CI

on:
  push:
    branches: [ main, PHP8 ]
  pull_request:
    branches: [ main ]

jobs:
  # 7.4 is the default
  UNIT-TESTS-74:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED

  UNIT-TESTS-COVERAGE-74:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      run-php-unit-coverage: true
      # Only wish to phpdbg with coverage enabled, no need to run tests without also
      run-php-unit: false
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED

  UNIT-TESTS-73:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      php-version: 7.3
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED

  UNIT-TESTS-80:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      php-version: 8.0
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED

  UNIT-TESTS-80-WITH-JIT:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      php-version: 8.0
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED
      coverage: none
      ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M

  UNIT-TESTS-SS47:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      silverstripe-version: 4.7
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED

  UNIT-TESTS-SS48:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      silverstripe-version: 4.8
      test-config-flag: UNIT_TESTING_FTS_CONFIG_ENABLED

  LINTING:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      run-php-lint: true
      run-phpstan: true
      run-todo: true
      run-php-unit: false
      run-duplicate-code-check: true

