name: Module CI

on:
  push:
    branches: [ main, CI3 ]
  pull_request:
    branches: [ main ]
jobs:
  ci1:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
  ci2:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      run-php-lint: true
      run-phpstan: true
      run-todo: true
    
