name: Module CI

on:
  push:
    branches: [ main, CI3 ]
  pull_request:
    branches: [ main ]
jobs:

  # 7.4 is the default
  CI-UNIT-TESTS-7.4:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main

  CI-UNIT-TESTS-7.3:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      php-version: 7.3

  CI-LINTING:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      run-php-lint: true
      run-phpstan: true
      run-todo: true
      run-php-unit: false

