name: Module CI

on:
  push:
    branches: [ main, CI3 ]
  pull_request:
    branches: [ main ]

env:
  UNIT_TESTING_FTS_CONFIG_ENABLED: 1
  BUILD_CONFIGURATION: Release

jobs:
  testenv:
    steps:
      - name: Check env within freetextsearch CI
        run: |
          env
          echo In actions workflow, We use the global workflow variable $BUILD_CONFIGURATION



  # 7.4 is the default
  UNIT-TESTS-74:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main

  UNIT-TESTS-COVERAGE-74:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      run-php-unit-coverage: true
      run-php-unit: false

  UNIT-TESTS-73:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      php-version: 7.3

  UNIT-TESTS-SS47:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      silverstripe-version: 4.7

  UNIT-TESTS-SS48:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      silverstripe-version: 4.8

  LINTING:
    uses: gordonbanderson/actions/.github/workflows/silverstripemodule.yml@main
    with:
      run-php-lint: true
      run-phpstan: true
      run-todo: true
      run-php-unit: false
      run-duplicate-code-check: true

